# Generated by Django 4.1.7 on 2023-04-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_card_delete_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='seller',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
