# Generated by Django 4.1.7 on 2023-05-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_card_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
